name: 'pr-enforcer'
description: 'Wait for GitHub Status Checks'
author: 'clowtown@gmail.com'
branding:
  color: green
  icon: check
inputs:
  token:
    description: 'GitHub token for reading the status check runs'
    required: true
  interval:
    description: 'Interval or period in seconds to poll GitHub Check Runs'
    required: false
    default: "10"
  timeout:
    description: 'Timeout in seconds to poll GitHub Check Runs'
    required: false
    default: "3600"
  ignore:
    description: 'GitHub checks that should be ignored (default ignores the current job)'
  exhaustive:
    description: 'Evaluate all check runs until they finish, do not fail fast'
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Setup Python version 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
        architecture: "x64"
    - name: 'evaluate checks'
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install --trusted-host=pypi.python.org --trusted-host pypi.org --trusted-host files.pythonhosted.org wheel
        pip install --trusted-host=pypi.python.org --trusted-host pypi.org --trusted-host files.pythonhosted.org -r ${GITHUB_ACTION_PATH}/requirements.txt
        python ${GITHUB_ACTION_PATH}/cli.py --token ${{ inputs.token }} --repository "${{github.repository}}" --branch "${{github.head_ref}}" --interval ${{ inputs.interval }} --timeout ${{ inputs.timeout }} --name "${{github.job}}" --ignore "${{ inputs.ignore }}" ${{ inputs.exhaustive == 'true' && '--exhaustive' || ''}} ${{ runner.debug && '--debug' || ''}}
